### ISSUE TITLE
node v8.0.0 issue

### ISSUE THREAD

**Issue by amit777** [mscdex/mmmagic#105]
hi, I'm getting this error in my logs after upgrading from v7.9.0 to 8.0.0.  I've tried deleting my node_modules directory and rebuilding, but it seems to persist:

```
Error: The module '/opt/app/node_modules/mmmagic/build/Release/magic.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/app/node_modules/mmmagic/lib/index.js:3:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)


```

**Comment by mscdex** [comment]
You completely removed /opt/app/node_modules ? I don't know what else to suggest, there must be an old copy staying behind somehow...

**Comment by amit777** [comment]
I tried a couple times.. but this time, i actually deleted all the pm2 apps and then started them again, and that seems to have fixed it.  sorry for the false report!
