### ISSUE TITLE
npm install always failed

### ISSUE THREAD

**Issue by Pei116** [mscdex/mmmagic#111]
I'm using node v8.1.4, npm v5.0.3, python 2.7.13 and MSVS 2015 in Windows 10.
When I try `npm install`, it fails with following error messages. I believe it's because of mmmagic.

```
> mmmagic@0.3.5 install F:\Sources\Web\glimpsable_old\node_modules\mmmagic
> node-gyp rebuild

F:\Sources\Web\glimpsable_old\node_modules\mmmagic>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  apprentice.c
  apptype.c
  ascmagic.c
  cdf.c
  cdf_time.c
  compress.c
  encoding.c
  fsmagic.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\ascmagic.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagi
c\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\ascmagic.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\apprentice.c) [F:\Sources\Web\glimpsable_old\node_modules\mmma
gic\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\apprentice.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\ascmagic.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\apprentice.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\compress.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagi
c\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\compress.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\compress.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\apptype.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic
\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\apptype.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\apptype.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\cdf_time.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagi
c\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\cdf_time.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\cdf_time.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\fsmagic.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic
\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\fsmagic.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\fsmagic.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  funcs.c
  is_tar.c
  magic.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\encoding.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagi
c\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\encoding.c)
  print.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\encoding.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  readcdf.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\cdf.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\bui
ld\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\cdf.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\cdf.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  readelf.c
  softmagic.c
  asctime_r.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\funcs.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\b
uild\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\funcs.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\funcs.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\readcdf.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic
\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\readcdf.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\readcdf.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\print.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\b
uild\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\print.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\print.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  asprintf.c
  ctime_r.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\is_tar.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\
build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\is_tar.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\is_tar.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\softmagic.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmag
ic\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\softmagic.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\softmagic.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  getline.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\readelf.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic
\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\readelf.c)
  pread.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\readelf.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  strlcat.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\asctime_r.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmag
ic\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\asctime_r.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\asctime_r.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  strlcpy.c
  vasprintf.c
..\..\..\deps\libmagic\src\vasprintf.c(35): warning C4013: 'vsnprintf' undefined; assuming extern returning int [F:\Sou
rces\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\magic.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\b
uild\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\magic.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\magic.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\asprintf.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagi
c\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\asprintf.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\asprintf.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\getline.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic
\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\getline.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\getline.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\ctime_r.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic
\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\ctime_r.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\ctime_r.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\strlcat.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic
\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\strlcat.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\strlcat.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\pread.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\b
uild\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\pread.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\pread.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefi
nition (compiling source file ..\..\..\deps\libmagic\src\strlcpy.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic
\build\deps\libmagic\libmagic.vcxproj]
  F:\Sources\Web\glimpsable_old\node_modules\mmmagic\deps\libmagic\config\win\config.h(358): note: see previous definit
  ion of 'snprintf' (compiling source file ..\..\..\deps\libmagic\src\strlcpy.c)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro defin
ition of snprintf conflicts with Standard Library function declaration (compiling source file ..\..\..\deps\libmagic\sr
c\strlcpy.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  pcre_byte_order.c
  pcre_chartables.c
  pcre_compile.c
  pcre_config.c
  pcre_dfa_exec.c
  pcre_exec.c
  pcre_fullinfo.c
  pcre_get.c
..\..\..\..\deps\libmagic\pcre\pcre_dfa_exec.c(1662): warning C4146: unary minus operator applied to unsigned type, res
ult still unsigned [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_dfa_exec.c(1708): warning C4146: unary minus operator applied to unsigned type, res
ult still unsigned [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_dfa_exec.c(1752): warning C4146: unary minus operator applied to unsigned type, res
ult still unsigned [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_dfa_exec.c(1793): warning C4146: unary minus operator applied to unsigned type, res
ult still unsigned [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(4145): warning C4244: '+=': conversion from '__int64' to 'int', possible
loss of data [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(5250): warning C4244: 'initializing': conversion from '__int64' to 'int',
 possible loss of data [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
  pcre_globals.c
  pcre_jit_compile.c
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(5251): warning C4244: 'initializing': conversion from '__int64' to 'int',
 possible loss of data [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_exec.c(656): warning C4244: 'initializing': conversion from '__int64' to 'int', pos
sible loss of data [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(5332): warning C4244: 'initializing': conversion from '__int64' to 'int',
 possible loss of data [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
..\..\..\..\deps\libmagic\pcre\pcre_compile.c(5333): warning C4244: 'initializing': conversion from '__int64' to 'int',
 possible loss of data [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
  pcre_maketables.c
  pcre_newline.c
  pcre_ord2utf8.c
  pcre_refcount.c
  pcre_string_utils.c
  pcre_study.c
  pcre_tables.c
  pcre_ucd.c
  pcre_valid_utf8.c
  pcre_version.c
  pcre_xclass.c
  pcreposix.c
f:\sources\web\glimpsable_old\node_modules\mmmagic\deps\libmagic\pcre\sljit\sljitNativeX86_64.c(388): warning C4244: '=
': conversion from 'sljit_sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\deps\libmagic\pcr
e\pcre_jit_compile.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
f:\sources\web\glimpsable_old\node_modules\mmmagic\deps\libmagic\pcre\sljit\sljitNativeX86_64.c(584): warning C4244: '=
': conversion from 'sljit_sw' to 'sljit_ub', possible loss of data (compiling source file ..\..\..\..\deps\libmagic\pcr
e\pcre_jit_compile.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
f:\sources\web\glimpsable_old\node_modules\mmmagic\deps\libmagic\pcre\sljit\sljitNativeX86_64.c(586): warning C4244: '=
': conversion from 'sljit_sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\deps\libmagic\pcr
e\pcre_jit_compile.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
f:\sources\web\glimpsable_old\node_modules\mmmagic\deps\libmagic\pcre\sljit\sljitNativeX86_64.c(593): warning C4244: '=
': conversion from 'sljit_sw' to 'sljit_ub', possible loss of data (compiling source file ..\..\..\..\deps\libmagic\pcr
e\pcre_jit_compile.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
f:\sources\web\glimpsable_old\node_modules\mmmagic\deps\libmagic\pcre\sljit\sljitNativeX86_64.c(599): warning C4244: '=
': conversion from 'sljit_sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\deps\libmagic\pcr
e\pcre_jit_compile.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
f:\sources\web\glimpsable_old\node_modules\mmmagic\deps\libmagic\pcre\sljit\sljitNativeX86_64.c(605): warning C4244: '=
': conversion from 'sljit_sw' to 'sljit_ub', possible loss of data (compiling source file ..\..\..\..\deps\libmagic\pcr
e\pcre_jit_compile.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
f:\sources\web\glimpsable_old\node_modules\mmmagic\deps\libmagic\pcre\sljit\sljitNativeX86_64.c(607): warning C4244: '=
': conversion from 'sljit_sw' to 'short', possible loss of data (compiling source file ..\..\..\..\deps\libmagic\pcre\p
cre_jit_compile.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
f:\sources\web\glimpsable_old\node_modules\mmmagic\deps\libmagic\pcre\sljit\sljitNativeX86_64.c(609): warning C4244: '=
': conversion from 'sljit_sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\deps\libmagic\pcr
e\pcre_jit_compile.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
f:\sources\web\glimpsable_old\node_modules\mmmagic\deps\libmagic\pcre\sljit\sljitNativeX86_64.c(742): warning C4244: '=
': conversion from 'sljit_sw' to 'sljit_si', possible loss of data (compiling source file ..\..\..\..\deps\libmagic\pcr
e\pcre_jit_compile.c) [F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\deps\libmagic\pcre\libpcre.vcxproj]
  win_delay_load_hook.cc
  libpcre.vcxproj -> F:\Sources\Web\glimpsable_old\node_modules\mmmagic\build\Release\\libpcre.lib
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Sources\Web\glimpsable_old\node_modules\mmmagic
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mscdex** [comment]
Is that the actual console output or is that from the npm log file? If it's not the former, post that instead since that is where you'll find the error that actually caused the build to fail.

**Comment by Pei116** [comment]
Hey, it's from the console output.

**Comment by mscdex** [comment]
Oh I see the problem now, try upgrading `mmmagic` to the latest version.

**Comment by Pei116** [comment]
Actually I didn't have a mmmagic in dependencies but it was pulled from other module, I think.
Anyway I've installed mmmagic latest version and it works like a charm!

**Comment by mscdex** [comment]
Cool, thanks for the update.
