### ISSUE TITLE
npm install fails on mac

### ISSUE THREAD

**Issue by itsTeknas** [mscdex/mmmagic#116]
```
$ npm install mmmagic


> mmmagic@0.4.5 install /Users/Sanket/WebstormProjects/nuphi-express/node_modules/mmmagic
> node-gyp rebuild

  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/compress.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/der.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/encoding.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/fsmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/funcs.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/is_tar.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/magic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/print.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readcdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readelf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/softmagic.o
  LIBTOOL-STATIC Release/magic.a
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_byte_order.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_chartables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_compile.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_config.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_dfa_exec.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_exec.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_fullinfo.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_get.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_globals.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_jit_compile.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_maketables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_newline.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_ord2utf8.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_refcount.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_string_utils.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_study.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_tables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_ucd.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_valid_utf8.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_version.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_xclass.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcreposix.o
  LIBTOOL-STATIC Release/pcre.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/pcre.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Sanket/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/Sanket/.nvm/versions/node/v7.10.0/bin/node" "/Users/Sanket/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Sanket/WebstormProjects/nuphi-express/node_modules/mmmagic
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.4.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.4.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Sanket/.npm/_logs/2017-09-13T09_59_05_230Z-debug.log
```

**Comment by mscdex** [comment]
This is more of a [node-gyp](https://github.com/nodejs/node-gyp) issue, but google suggests it has to do with the wrong version of Python being used. You need to make sure 2.x is being used when installing/building node addons. I think you can do this one of two ways:

```
npm config set python /path/to/executable/python2.7
```

or:

```
npm install --python=python2.7
```

Or whatever the binary name is for your version of Python 2.x.

**Comment by itsTeknas** [comment]
Yup i have python 3.6 installed. Thanks, that should solve it.
