### ISSUE TITLE
Cannot find module '../build/Release/magic' from 'index.js' during Jest tests

### ISSUE THREAD

**Issue by VMois** [mscdex/mmmagic#128]
Hi. I have the following error, while running jest tests:
```
Cannot find module '../build/Release/magic' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/mmmagic/lib/index.js:3:13)
```
If I run an app as normal, it works without problems, but when trying to run Jest tests throws error above. Maybe someone has a similar issue. Thank you.
NodeJS: 8.11,
default_configuration: 'Release'

**Comment by VMois** [comment]
Found solution - https://stackoverflow.com/questions/50778404/cannot-find-module-build-release-magic-from-index-js-during-jest-tests/50802300#50802300
