### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by lisong** [mscdex/mmmagic#131]
```
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at _errnoException (util.js:1022:11)
gyp ERR! stack     at TLSWrap.onread (net.js:628:25)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/tablee/.nvm/versions/node/v8.10.0/bin/node" "/Users/tablee/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tablee/workspaces/code-push-server/node_modules/mmmagic
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
[2018-09-08T07_53_26_000Z-debug.log](https://github.com/mscdex/mmmagic/files/2363134/2018-09-08T07_53_26_000Z-debug.log)

**Comment by mscdex** [comment]
That's an npm/node-gyp error, so this would be better posted to one of their issue trackers. This addon's build script does not download anything. If I had to take a guess, npm/node-gyp is probably failing to download the node C++ headers tarball for the version of node you're using if this is the first addon you're compiling since switching to this version of node.
