### ISSUE TITLE
Build on Nodejs 10 on windows is broken

### ISSUE THREAD

**Issue by Apollon77** [mscdex/mmmagic#135]
mmmagic is usedf as one of the deps in one of my project ... I get the following error in nodejs 10.13.0 with npm 6.4.1 on Appveyor:

```
> mmmagic@0.5.2 install C:\projects\ioBroker.sql\node_modules\mmmagic
> node-gyp rebuild
C:\projects\ioBroker.sql\node_modules\mmmagic>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  apprentice.c
  apptype.c
  ascmagic.c
  cdf.c
  cdf_time.c
..\..\..\deps\libmagic\src\cdf.c(1210): warning C4013: 'snprintf' undefined; assuming extern returning int [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  compress.c
..\..\..\deps\libmagic\src\cdf_time.c(174): warning C4013: 'snprintf' undefined; assuming extern returning int [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  der.c
  encoding.c
..\..\..\deps\libmagic\src\der.c(218): warning C4013: 'snprintf' undefined; assuming extern returning int [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  fsmagic.c
  funcs.c
  is_tar.c
  magic.c
  print.c
  readcdf.c
  readelf.c
..\..\..\deps\libmagic\src\readcdf.c(133): warning C4013: 'strcasestr' undefined; assuming extern returning int [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\readcdf.c(133): warning C4047: '!=' : 'int' differs in levels of indirection from 'void *' [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
..\..\..\deps\libmagic\src\readcdf.c(241): warning C4133: 'function' : incompatible types - from 'long *' to 'const time_t *' [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  softmagic.c
  fmtcheck.c
..\..\..\deps\libmagic\src\softmagic.c(462): warning C4013: 'snprintf' undefined; assuming extern returning int [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  asctime_r.c
  asprintf.c
  ctime_r.c
  dprintf.c
  getline.c
  gmtime_r.c
  localtime_r.c
  pread.c
  snprintf.c
  strcasestr.c
  strlcat.c
  strlcpy.c
  vasprintf.c
  regex.c
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regcomp.c(572): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regcomp.c(575): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regcomp.c(590): warning C4018: '<=' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regcomp.c(1107): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regcomp.c(1110): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regcomp.c(1560): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regcomp.c(1563): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regexec.c(524): warning C4018: '>' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regexec.c(539): warning C4018: '>=' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regexec.c(549): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regexec.c(874): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regexec.c(892): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regexec.c(920): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
c:\projects\iobroker.sql\node_modules\mmmagic\deps\libmagic\msvc\libgnurx-2.5\regexec.c(1439): warning C4018: '<' : signed/unsigned mismatch (..\..\..\deps\libmagic\msvc\libgnurx-2.5\regex.c) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\deps\libmagic\libmagic.vcxproj]
  win_delay_load_hook.cc
  libmagic.vcxproj -> C:\projects\ioBroker.sql\node_modules\mmmagic\build\Release\\libmagic.lib
  binding.cc
  win_delay_load_hook.cc
c:\users\appveyor\.node-gyp\10.13.0\include\node\v8.h(2570): error C2144: syntax error : 'int' should be preceded by ';' (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
c:\users\appveyor\.node-gyp\10.13.0\include\node\v8.h(2570): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
c:\users\appveyor\.node-gyp\10.13.0\include\node\v8.h(4273): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
c:\users\appveyor\.node-gyp\10.13.0\include\node\v8.h(4276): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
c:\users\appveyor\.node-gyp\10.13.0\include\node\v8.h(4362): error C2610: 'v8::WasmModuleObjectBuilderStreaming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
c:\users\appveyor\.node-gyp\10.13.0\include\node\v8.h(4367): error C2610: 'v8::WasmModuleObjectBuilderStreaming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
c:\users\appveyor\.node-gyp\10.13.0\include\node\v8.h(4632): error C2146: syntax error : missing ';' before identifier 'size_t' (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
c:\users\appveyor\.node-gyp\10.13.0\include\node\v8.h(4632): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
C:\Users\appveyor\.node-gyp\10.13.0\include\node\node_buffer.h(36): error C2597: illegal reference to non-static member 'v8::TypedArray::kMaxLength' (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
C:\Users\appveyor\.node-gyp\10.13.0\include\node\node_buffer.h(36): error C2440: 'initializing' : cannot convert from 'unknown' to 'const unsigned int' (..\src\binding.cc) [C:\projects\ioBroker.sql\node_modules\mmmagic\build\magic.vcxproj]
          There is no context in which this conversion is possible
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\ioBroker.sql\node_modules\mmmagic
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmmagic@0.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by mscdex** [comment]
I just re-ran the latest commit with our AppVeyor setup and it's [still passing](https://ci.appveyor.com/project/mscdex/mmmagic/build/job/rn0e26mw21p0rjv3), so I'm not sure why you're having that problem.

**Comment by mscdex** [comment]
Is it possible you're using an older compiler? For node v10.x you need at least VS2015.

**Comment by Apollon77** [comment]
Strange ... I rerun it on my side too

**Comment by Apollon77** [comment]
Ok, I will check appveyor config, but was never a problem before ...
https://ci.appveyor.com/project/Apollon77/iobroker-sql-tvcxe/builds/20140545/job/34cac61wqmw2n1o4

**Comment by Apollon77** [comment]
current configured build environment is VS 2015

**Comment by mscdex** [comment]
The project for the log you linked to shows [VS 2013 is currently configured for all node versions](https://github.com/ioBroker/ioBroker.sql/blob/dc090e6e63442c36c80e030d92407303c22d9734/appveyor.yml#L2).

**Comment by Apollon77** [comment]
grrrr ... did not saw the it was overwritten in configfile :( Sorry, rebuilding
