### ISSUE TITLE
Error while importing module

### ISSUE THREAD

**Issue by surdu** [mscdex/mmmagic#150]
I'm running an Express server on an Ubuntu docker instance, and when I try to import the module I get:

```
internal/modules/cjs/loader.js:1206
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error loading shared library /app/node_modules/mmmagic/build/Release/magic.node: Exec format error
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/node_modules/mmmagic/lib/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/routes/product.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/app.js:11:23)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```

**Comment by mscdex** [comment]
Did you copy the node_modules from another system where the modules was originally installed? I'm betting it was copied either from a different OS (e.g. from macOS to Linux) or from a different, incompatible CPU architecture.

**Comment by surdu** [comment]
Hmmm.... You might be onto something 😃 I'll double check my docker configuration tonight and get back to you.
