### ISSUE TITLE
Fails to build on node.js 0.11.8 / OS X 10.9 | Travis CI

### ISSUE THREAD

**Issue by SaltwaterC** [mscdex/mmmagic#16]
```bash
~/P/h/src (future) node -v
v0.11.8
~/P/h/src (future) npm -v
1.3.13
~/P/h/src (future) npm install mmmagic
npm http GET https://registry.npmjs.org/mmmagic
npm http 304 https://registry.npmjs.org/mmmagic

> mmmagic@0.3.4 install /Users/SaltwaterC/Projects/http-request/src/node_modules/mmmagic
> node-gyp rebuild

[output about CC(target)]

LIBTOOL-STATIC Release/pcre.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: Release/obj.target/libpcre/deps/libmagic/pcre/pcre_string_utils.o has no symbols
  CXX(target) Release/obj.target/magic/src/magic.o
../src/magic.cc:12:5: error: unknown type name 'uv_work_t'
    uv_work_t request;
    ^
../src/magic.cc:32:22: error: expected class name
class Magic : public ObjectWrap {
                     ^
../src/magic.cc:54:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments& args) {
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:140:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/magic.cc:102:43: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> DetectFile(const Arguments& args) {
                                          ^~~~~~~~~
                                          v8::internal::Arguments
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:140:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/magic.cc:139:39: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> Detect(const Arguments& args) {
                                      ^~~~~~~~~
                                      v8::internal::Arguments
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:140:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/magic.cc:184:28: error: unknown type name 'uv_work_t'
    static void DetectWork(uv_work_t* req) {
                           ^
../src/magic.cc:222:29: error: unknown type name 'uv_work_t'
    static void DetectAfter(uv_work_t* req) {
                            ^
../src/magic.cc:261:44: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> SetFallback(const Arguments& args) {
                                           ^~~~~~~~~
                                           v8::internal::Arguments
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:140:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/magic.cc:55:19: error: no matching constructor for initialization of
      'v8::HandleScope'
      HandleScope scope;
                  ^
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:756:3: note: candidate constructor
      not viable: requires single argument 'isolate', but no arguments were provided
  HandleScope(Isolate* isolate);
  ^
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:783:3: note: candidate constructor
      not viable: requires 1 argument, but 0 were provided
  HandleScope(const HandleScope&);
  ^
../src/magic.cc:96:12: error: no member named 'Wrap' in 'Magic'
      obj->Wrap(args.This());
      ~~~  ^
../src/magic.cc:97:12: error: no member named 'Ref' in 'Magic'
      obj->Ref();
      ~~~  ^
../src/magic.cc:103:19: error: no matching constructor for initialization of
      'v8::HandleScope'
      HandleScope scope;
                  ^
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:756:3: note: candidate constructor
      not viable: requires single argument 'isolate', but no arguments were provided
  HandleScope(Isolate* isolate);
  ^
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:783:3: note: candidate constructor
      not viable: requires 1 argument, but 0 were provided
  HandleScope(const HandleScope&);
  ^
../src/magic.cc:104:20: error: use of undeclared identifier 'ObjectWrap'
      Magic* obj = ObjectWrap::Unwrap<Magic>(args.This());
                   ^
../src/magic.cc:104:39: error: 'Magic' does not refer to a value
      Magic* obj = ObjectWrap::Unwrap<Magic>(args.This());
                                      ^
../src/magic.cc:32:7: note: declared here
class Magic : public ObjectWrap {
      ^
../src/magic.cc:123:47: error: 'New' is a private member of 'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
      baton->callback = Persistent<Function>::New(callback);
                                              ^
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:733:23: note: declared private
      here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/magic.cc:123:59: error: too few arguments to function call, expected 2, have 1
      baton->callback = Persistent<Function>::New(callback);
                        ~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:733:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8config.h:301:20: note: expanded from
      macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../src/magic.cc:130:34: error: use of undeclared identifier 'uv_default_loop'
      int status = uv_queue_work(uv_default_loop(),
                                 ^
../src/magic.cc:140:19: error: no matching constructor for initialization of
      'v8::HandleScope'
      HandleScope scope;
                  ^
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:756:3: note: candidate constructor
      not viable: requires single argument 'isolate', but no arguments were provided
  HandleScope(Isolate* isolate);
  ^
/Users/SaltwaterC/.node-gyp/0.11.8/deps/v8/include/v8.h:783:3: note: candidate constructor
      not viable: requires 1 argument, but 0 were provided
  HandleScope(const HandleScope&);
  ^
../src/magic.cc:141:20: error: use of undeclared identifier 'ObjectWrap'
      Magic* obj = ObjectWrap::Unwrap<Magic>(args.This());
                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/magic/src/magic.o] Error 1
gyp ERR! build error
```

Travis CI starts to throw errors about mmmagic right about here: https://travis-ci.org/SaltwaterC/http-request/jobs/14590353#L158

**Comment by mscdex** [comment]
The master branch should now have compatibility with node v0.10.x and v0.11.13+ via nan. Let me know if any of you run into any problems.

**Comment by cusspvz** [comment]
@mscdex fails with current master

```bash
MacBook-Pro-de-JM:/path/to/private/project$ npm i mscdex/mmmagic
npm WARN engine mmmagic@0.3.12: wanted: {"node":">=0.6.0"} (current: {"node":"0.11.15-pre","npm":"2.1.11"})
-
> mmmagic@0.3.12 install /path/to/private/project/node_modules/mmmagic
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:66:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:152:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:95:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:725:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:998:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1166:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:475:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /path/to/private/project/node_modules/mmmagic
gyp ERR! node -v v0.11.15-pre
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "mscdex/mmmagic"
npm ERR! node v0.11.15-pre
npm ERR! npm  v2.1.11
npm ERR! code ELIFECYCLE

npm ERR! mmmagic@0.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmmagic@0.3.12 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/private/project/npm-debug.log
```
