### ISSUE TITLE
Cannot build mmmagic

### ISSUE THREAD

**Issue by lowgos** [mscdex/mmmagic#164]
I've been having a hard time debugging a build error that is related to `mmmagic`.

- I'm on a fresh install of Fedora 36
- I'm using `fish` shell
- A potential key point is `fnm`, a wrapper around `nvm`.

Here is the complete log, I just replaced some personal pathes with `[...]`: 

``` bash
npm ERR! code 1
npm ERR! path /home/gcho/[...]/node_modules/mmmagic
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/home/gcho/[...]/node_modules/mmmagic/build'
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/compress.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/der.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/encoding.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/fsmagic.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/funcs.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/is_tar.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/magic.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/print.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/readcdf.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/readelf.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/softmagic.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/fmtcheck.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/strlcat.o
npm ERR!   CC(target) Release/obj.target/libmagic/deps/libmagic/src/strlcpy.o
npm ERR!   AR(target) Release/obj.target/deps/libmagic/magic.a
npm ERR!   COPY Release/magic.a
npm ERR!   CXX(target) Release/obj.target/magic/src/binding.o
npm ERR! make: Leaving directory '/home/gcho/[...]/node_modules/mmmagic/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/gcho/.fnm/node-versions/v16.14.2/installation/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/gcho/[...]/node_modules/mmmagic/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/gcho/.fnm/node-versions/v16.14.2/installation/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/gcho/.cache/node-gyp/16.14.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/gcho/.cache/node-gyp/16.14.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/gcho/.fnm/node-versions/v16.14.2/installation/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/gcho/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/gcho/[...]/node_modules/mmmagic',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: g++: No such file or directory
npm ERR! make: *** [magic.target.mk:124: Release/obj.target/magic/src/binding.o] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/gcho/.fnm/node-versions/v16.14.2/installation/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.17.1-300.fc36.x86_64
npm ERR! gyp ERR! command "/home/gcho/.fnm/node-versions/v16.14.2/installation/bin/node" "/home/gcho/.fnm/node-versions/v16.14.2/installation/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/gcho/[...]/node_modules/mmmagic
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by lowgos** [comment]
I've tried starting my Nest project inside Docker in order to eliminate some environment related issues maybe.
mmmagic still causes an issue but this time on runtime:

``` bash
Error: Cannot find module '../build/Release/magic'
Require stack:
- /app/node_modules/mmmagic/lib/index.js
...
- /app/dist/src/modules/app.module.js
- /app/dist/src/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/mmmagic/lib/index.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

The Node version is the same, I don't know what to do as it prevents me from doing my job.
I think I will go back to Arch linux, yesterday it was working well on this distro, it may be related to Fedora idk...

**Comment by mscdex** [comment]
Not sure what to tell you, but the log clearly shows it having a problem finding your c++ compiler (g++), although your c compiler was found (since it was seemingly able to compile the libmagic dependency).

**Comment by lowgos** [comment]
I've installed g++ through Fedora's package manager and it fixed the problem, you were right !
Definitely weird that no clean error message comes through in this case, or that the library doesn't check for this kind of system dependency before crashing.
But I guess that my installation too fresh :sweat_smile: 

Thank you for the quick answer !
