### ISSUE TITLE
npm install mmmagic fails on windows 

### ISSUE THREAD

**Issue by sunder-asuri** [mscdex/mmmagic#175]
I am getting this error when I run `npm install mmmagic`

```
npm ERR! code 1
npm ERR! path C:\Users\Sunder Asuri\Documents\mmmagic-test\node_modules\mmmagic
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.12.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.1 found at "C:\Users\Sunder Asuri\AppData\Local\Programs\Python\Python312\python.exe"
npm ERR! gyp info find VS using VS2022 (17.8.34330.188) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\Sunder Asuri\AppData\Local\Programs\Python\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\Sunder Asuri\\AppData\\Roaming\\nvm\\v18.12.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Sunder Asuri\\Documents\\mmmagic-test\\node_modules\\mmmagic\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Sunder Asuri\\AppData\\Roaming\\nvm\\v18.12.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Sunder Asuri\\AppData\\Local\\node-gyp\\Cache\\18.12.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Sunder Asuri\\AppData\\Local\\node-gyp\\Cache\\18.12.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Sunder Asuri\\AppData\\Roaming\\nvm\\v18.12.0\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Sunder Asuri\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.12.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Sunder Asuri\\Documents\\mmmagic-test\\node_modules\\mmmagic',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\Sunder Asuri\\Documents\\mmmagic-test\\node_modules\\mmmagic\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\Sunder Asuri\AppData\Roaming\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "C:\Users\Sunder Asuri\AppData\Roaming\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "C:\Users\Sunder Asuri\AppData\Roaming\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Sunder Asuri\AppData\Roaming\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:284:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22631
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sunder Asuri\\AppData\\Roaming\\nvm\\v18.12.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Sunder Asuri\Documents\mmmagic-test\node_modules\mmmagic
npm ERR! gyp ERR! node -v v18.12.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
```

Am I missing anything?

**Comment by mscdex** [comment]
The [node-gyp README](https://github.com/nodejs/node-gyp?tab=readme-ov-file#installation) mentions that you need node-gyp >= v10 if you're using Python >= 3.12. Upgrade your copy of node to at least the latest node v18.x (currently v18.20.4) or a newer branch to get a version of npm that has node-gyp >= v10.
