### ISSUE TITLE
build/Relase/magic.node Invalid ELF Header

### ISSUE THREAD

**Issue by Paulbliudzius** [mscdex/mmmagic#41]
I have been trying to deploy http-request module, which uses this, and when it does, I get 

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: ../http-request/node_modules/mmmagic/build/Release/magic.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (../http-request/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by mscdex** [comment]
Can you provide more information? Node/iojs version? Platform and/or distro? I have not run into this error before. Are you sure it compiled successfully? What does `file ../http-request/node_modules/mmmagic/build/Release/magic.node` output?
