### ISSUE TITLE
Error installing on Windows

### ISSUE THREAD

**Issue by PavelPolyakov** [mscdex/mmmagic#42]
hi,

When installing the module on Windows I see the next:

~~~
$ npm install mmmagic
-
> mmmagic@0.3.13 install d:\projects\myproject\git\node_modules\mmmagic
> node-gyp rebuild


d:\projects\myproject\git\node_modules\mmmagic>node "c:\Program Files (x86)\no
dejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: x64/node.lib local checksum 8b539aaaa72b00aa6b92b2dc9ee377
159eaed4f01d0b7264a3c8ce06ac37971b not match remote 1c93d92da38a85a36b1e93556d16
024d7ca6d342f9bfb9aafe066427a35c4928
gyp ERR! stack     at deref (c:\Program Files (x86)\nodejs\node_modules\npm\node
_modules\node-gyp\lib\install.js:299:20)
gyp ERR! stack     at Request.<anonymous> (c:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\install.js:383:24)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (c:\Program Files (x86)\nodejs
\node_modules\npm\node_modules\request\request.js:1096:12)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:907:16
gyp ERR! stack     at process._tickCallback (node.js:372:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\projects\myproject\git\node_modules\mmmagic
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mmmagic"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! mmmagic@0.3.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.3.13 install script.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.
~~~

What could help me?

**Comment by mscdex** [comment]
This is a node/npm issue. You should update to node v0.12 and retry. If that still doesn't help, you should file an issue on npm's issue tracker [here](https://github.com/npm/npm/issues/new).
