### ISSUE TITLE
Build fails on SunOS 5.11

### ISSUE THREAD

**Issue by julianlam** [mscdex/mmmagic#52]
Thanks for your time -- attached npm stack trace. Let me know if you need addl. debug info.

```
> mmmagic@0.3.14 install /root/nodebb/node_modules/mmmagic
> node-gyp rebuild

make: Entering directory '/root/nodebb/node_modules/mmmagic/build'
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
../deps/libmagic/src/cdf.c: In function 'cdf_read':
../deps/libmagic/src/cdf.c:303:2: warning: implicit declaration of function 'pread' [-Wimplicit-function-declaration]
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/compress.o
../deps/libmagic/src/compress.c: In function 'file_zmagic':
../deps/libmagic/src/compress.c:108:2: error: unknown type name 'sig_t'
../deps/libmagic/src/compress.c:113:11: warning: assignment makes integer from pointer without a cast [enabled by default]
../deps/libmagic/src/compress.c:140:2: warning: passing argument 2 of 'signal' makes pointer from integer without a cast [enabled by default]
In file included from /usr/include/signal.h:42:0,
                 from ../deps/libmagic/src/compress.c:48:
/usr/include/iso/signal_iso.h:63:15: note: expected 'void (*)(int)' but argument is of type 'int'
deps/libmagic/libmagic.target.mk:117: recipe for target 'Release/obj.target/libmagic/deps/libmagic/src/compress.o' failed
make: *** [Release/obj.target/libmagic/deps/libmagic/src/compress.o] Error 1
make: Leaving directory '/root/nodebb/node_modules/mmmagic/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/nodebb/node_modules/mmmagic
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! mmmagic@0.3.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.3.14 install script.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.
npm ERR! System SunOS 5.11
npm ERR! command "/opt/local/bin/node" "/opt/local/bin/npm" "install" "mmmagic"
npm ERR! cwd /root/nodebb
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by mscdex** [comment]
This is a [known issue upstream](http://bugs.gw.com/view.php?id=438) that has already been resolved. I was hoping they would have another release by now (since 5.22 in January of this year). I generally like to stick to releases, but I may have to just pull in current changes and do another mmmagic release if we don't see 5.23 soon...

**Comment by mscdex** [comment]
Ok someone already asked this on the file mailing list and [the developer said](http://mx.gw.com/pipermail/file/2015/001738.html) a new version should be coming within the next couple of weeks.

**Comment by julianlam** [comment]
Awesome, thanks for the update :)

**Comment by munish-daffodil** [comment]
I am getting same error on Ubuntu system. My Node version is 0.12.04. Please help.

**Comment by mscdex** [comment]
Ok, 5.23 is in master. Please give it a try and let me know if it solves things for you.
