### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by stringbeans** [mscdex/mmmagic#72]
While trying to npm install on an ec2 instance...

```
npm i mmmagic
npm WARN package.json holidayjs@0.1.0 No repository field.
-
> mmmagic@0.3.16 install /var/www/edvisor.io/node_modules/mmmagic
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 522 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/home/ubuntu/.nvm/versions/node/v0.12.3/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (/home/ubuntu/.nvm/versions/node/v0.12.3/lib/node_modules/npm/node_modules/request/request.js:1156:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "node" "/home/ubuntu/.nvm/versions/node/v0.12.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/edvisor.io/node_modules/mmmagic
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v0.12.3/bin/node" "/home/ubuntu/.nvm/versions/node/v0.12.3/bin/npm" "i" "mmmagic"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! mmmagic@0.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmmagic@0.3.16 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/edvisor.io/npm-debug.log
```

Other npm package installs work.

Using Node v0.12.3, npm 2.9.1

**Comment by stringbeans** [comment]
nevermind! network issue with the ec2 instance.
