### ISSUE TITLE
gyp: binding.gyp not found

### ISSUE THREAD

**Issue by jamesongithub** [mscdex/mmmagic#75]
getting this when trying to build mmmagic

```
17:29:14 { [Error: Command failed: /bin/sh -c npm rebuild
17:29:14 gyp: binding.gyp not found (cwd: ${PATH}/node_modules/mmmagic) while trying to load binding.gyp
17:29:14 gyp ERR! configure error 
17:29:14 gyp ERR! stack Error: `gyp` failed with exit code: 1
17:29:14 gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
17:29:14 gyp ERR! stack     at emitTwo (events.js:87:13)
17:29:14 gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
17:29:14 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
17:29:14 gyp ERR! System Linux 3.13.0-48-generic
17:29:14 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
17:29:14 gyp ERR! cwd ${PATH}/node_modules/mmmagic
17:29:14 gyp ERR! node -v v4.4.0
17:29:14 gyp ERR! node-gyp -v v3.3.0
17:29:14 gyp ERR! not ok 
17:29:14 
17:29:14 npm ERR! Linux 3.13.0-48-generic
17:29:14 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild"
17:29:14 npm ERR! node v4.4.0
17:29:14 npm ERR! npm  v2.14.20
17:29:14 npm ERR! code ELIFECYCLE
17:29:14 npm ERR! mmmagic@0.4.1 install: `node-gyp rebuild`
17:29:14 npm ERR! Exit status 1
17:29:14 npm ERR! 
17:29:14 npm ERR! Failed at the mmmagic@0.4.1 install script 'node-gyp rebuild'.
17:29:14 npm ERR! This is most likely a problem with the mmmagic package,
17:29:14 npm ERR! not with npm itself.
17:29:14 npm ERR! Tell the author that this fails on your system:
17:29:14 npm ERR!     node-gyp rebuild
17:29:14 npm ERR! You can get information on how to open an issue for this project with:
17:29:14 npm ERR!     npm bugs mmmagic
17:29:14 npm ERR! Or if that isn't available, you can get their info via:
17:29:14 npm ERR! 
17:29:14 npm ERR!     npm owner ls mmmagic
17:29:14 npm ERR! There is likely additional logging output above.
17:29:14 
17:29:14 npm ERR! Please include the following file with any support request:
17:29:14 npm ERR!     ${PATH}/npm-debug.log
17:29:14 ]
17:29:14   killed: false,
17:29:14   code: 1,
17:29:14   signal: null,
17:29:14   cmd: '/bin/sh -c npm rebuild' }
17:29:14 
17:29:14 An error occured while `npm-pkgr` ran.
17:29:14 You will find an `npm-debug.log` in `${PATH}` if `npm install` failed
17:29:14 
```

**Comment by mscdex** [comment]
How are you installing `mmmagic`?

**Comment by mscdex** [comment]
Also, can you post the full output from the console (not `npm-debug.log`)?

**Comment by jamesongithub** [comment]
hmm, it actually might be an issue w/ npm-pkgr that we are using. i'll close for now and reopen if we find out more.
