### ISSUE TITLE
mmmagic does not install on v0.10.36 and v0.12.9

### ISSUE THREAD

**Issue by ozette** [mscdex/mmmagic#78]
These are old versions of node I know, but I'm not in the position to update the software.
The readme says v0.10.0 or newer, but this doesn't seem to be the case.

output
```
[ozette@localhost dir]$ npm install --save mmmagic
npm http GET https://registry.npmjs.org/mmmagic
npm http 304 https://registry.npmjs.org/mmmagic
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> mmmagic@0.4.3 install /home/ozette/node_modules/mmmagic
> node-gyp rebuild

make: Entering directory '/home/magissa/experimental/spudu/node_modules/mmmagic/build'
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/compress.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/der.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/encoding.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/fsmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/funcs.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/is_tar.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/magic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/print.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readcdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readelf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/softmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/fmtcheck.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/strlcat.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/strlcpy.o
  AR(target) Release/obj.target/deps/libmagic/magic.a
  COPY Release/magic.a
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_byte_order.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_chartables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_compile.o
../deps/libmagic/pcre/pcre_compile.c: In function ‘add_to_class’:
../deps/libmagic/pcre/pcre_compile.c:3479:28: warning: ‘od’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       else if (oc >= start && od <= end) continue;
                            ^
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_config.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_dfa_exec.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_exec.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_fullinfo.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_get.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_globals.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_jit_compile.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_maketables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_newline.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_ord2utf8.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_refcount.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_string_utils.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_study.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_tables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_ucd.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_valid_utf8.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_version.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_xclass.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcreposix.o
  AR(target) Release/obj.target/deps/libmagic/pcre/pcre.a
  COPY Release/pcre.a
  CXX(target) Release/obj.target/magic/src/binding.o
In file included from ../src/binding.cc:3:0:
../node_modules/nan/nan.h:328:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
magic.target.mk:103: recipe for target 'Release/obj.target/magic/src/binding.o' failed
make: *** [Release/obj.target/magic/src/binding.o] Error 1
make: Leaving directory '/home/ozette/node_modules/mmmagic/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.13-100.fc21.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ozette/node_modules/mmmagic
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0


```

**Comment by mscdex** [comment]
How did you install node? If you *have to* stay on v0.10, you should at least try installing the latest v0.10 release (v0.10.44 as of this writing) and retry the install. Otherwise if you do not strictly need v0.10, you should install a newer, more modern version of node.

**Comment by ozette** [comment]
I installed node through my package manager (yum) on fedora 21 (EOL). GCC version 4.9.2.
v0.10.36 seems to be the latest packaged version of node for this EOL fedora _version_, so i can't update thorugh yum, but I installed [nvm](https://github.com/creationix/nvm) which allowed me to get the latest stable node version.

**Comment by mscdex** [comment]
My guess is that Fedora did not apply [this patch](https://github.com/nodejs/node/commit/881ac26f27f4ac9585d66c8d8a67d5b246a23d1b) to their external copy of v8 since they build with a shared, system copy of v8 instead of using what's bundled with node.

I'm glad to hear you found a solution though!
